### PR TITLE
Separately control CPython versions in nightly CI

### LINKED ISSUE #2226: Upgrade Python 3.8 jobs against pip's main branch in nightly CI to Python 3.9
Pip dropped Python 3.8 and now those jobs are failing every day. We could still suport Python 3.8 with older pips until it goes EOL, I suppose.

### PR DESCRIPTION
**Pull request by sirosen**
The pip versions being tested are controlled via a JSON array passed as
a string. Use the same mechanism to pass CPython versions to test.

This allows PR builds to continue to test 3.8 (EOL) and 3.9 (EOL soon)
while nightly builds will only run on 3.10+ .

Resolves #2226

##### Contributor checklist

- [x] ~Included tests for the changes.~
- [x] A change note is created in `changelog.d/` (see [`changelog.d/README.md`](https://github.com/jazzband/pip-tools/blob/main/changelog.d/#readme) for instructions) or the PR text says "no changelog needed".

##### Maintainer checklist

- [x] If no changelog is needed, apply the `skip-changelog` label.
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

### CODE REVIEW

**Review by webknjaz — APPROVED** [review]
Alright.. This is fine short-term but what I *really* want is to push matrix definitions *out* of the reusable workflows so the reusable workflow would only have one job with one python/os/arch combo. This worked really well for `reusable-tox.yml` and we should work towards moving in the direction of the same style.

When this is done, we'd be able to control pairs of pip+python more granularly, on the calling side.

File: changelog.d/2226.misc.md [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Narrow the CPython versions tested in nightly CI runs and separate these from
```
Comment (webknjaz) [inline changelog.d/2226.misc.md]: non-imperative plz?

Comment (sirosen) [reply changelog.d/2226.misc.md]: :+1: I'll fix it up.

**Comment by sirosen** [comment]
> This is fine short-term but what I really want is to push matrix definitions out of the reusable workflows so the reusable workflow would only have one job with one python/os/arch combo.

This sounds like a wonderful longer term solve. Let's queue it up as something to work on.

I'm not a huge fan of the current solution, but I saw it as the shortest path towards healthier CI. (And this was listed for 7.5.1 so I wanted to choose either "put in a relatively easy solution" or "explicitly move it to 7.5.2".)
