### PR TITLE
Link to genuine pull requests from README examples

### LINKED ISSUE #2240: Documentation: build failure with Sphinx 7.2.2
The documentation for `pip-tools` fails to build using the currently-specified version 7.2.2 of [Sphinx](https://github.com/sphinx-doc/sphinx/).

This appears to be due to an issue that has been resolved from version 7.2.3 of Sphinx: https://github.com/sphinx-doc/sphinx/pull/11523

#### Environment Versions

1. OS: Debian Linux (`forky` / `testing`)
1. Python version: `Python 3.13.7`
1. pip version: `pip 25.1`
1. pip-tools version: `pip-compile, version 7.5.1.dev28+dirty`

#### Steps to replicate

1. Set the working directory to the `docs` dir.
2. `pip install -r requirements.txt`
3. `pip install -e ..  # ensure pip-tools itself is installed as a package`
4. `sphinx-build -b html . _build`

#### Expected result
A complete successful HTML documentation build, with output in the `_build` directory.

#### Actual result
The build fails with the following traceback:

```
Traceback (most recent call last):
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
    ~~~~~~~~~~^^^^^^^^^^
               summary=__('targets for %d source files that are out of date') %
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               len(to_build))
               ^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ~~~~~~~~~^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/builders/__init__.py", line 498, in read_doc
    publisher.publish()
    ~~~~~~~~~~~~~~~~~^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     self.settings)
                                     ^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/io.py", line 105, in read
    self.parse()
    ~~~~~~~~~~^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/readers/__init__.py", line 76, in parse
    self.parser.parse(self.input, document)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/parsers.py", line 81, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 169, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
                                 input_source=document['source'])
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ~~~~~~~~~~~~~~~^
        context, state, transitions)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 2357, in explicit_markup
    self.explicit_list(blank_finish)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 2382, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
                                   ~~~~~~~~~~~~~~~~~~~~~~^
          self.state_machine.input_lines[offset:],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
          blank_finish=blank_finish,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
          match_titles=self.state_machine.match_titles)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 316, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      node=node, match_titles=match_titles)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/statemachine.py", line 233, in run
    context, next_state, result = self.check_line(
                                  ~~~~~~~~~~~~~~~^
        context, state, transitions)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/statemachine.py", line 445, in check_line
    return method(match, context, next_state)
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 2660, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
                             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 2367, in explicit_construct
    return method(self, expmatch)
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 2104, in directive
    return self.run_directive(
           ~~~~~~~~~~~~~~~~~~^
        directive_class, match, type_name, option_presets)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/docutils/parsers/rst/states.py", line 2154, in run_directive
    result = directive_instance.run()
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/ext/autodoc/directive.py", line 139, in run
    documenter.generate(more_content=self.content)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/ext/autodoc/__init__.py", line 1886, in generate
    return super().generate(more_content=more_content,
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
                            check_module=check_module,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
                            all_members=all_members)
                            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/ext/autodoc/__init__.py", line 869, in generate
    if not self.parse_name():
           ~~~~~~~~~~~~~~~^^
  File "<base-dir>/pip-tools/docs/.venv/lib/python3.13/site-packages/sphinx/ext/autodoc/__init__.py", line 388, in parse_name
    assert matched is not None
           ^^^^^^^^^^^^^^^^^^^
AssertionError
```

### LINKED ISSUE #2241: Fixup: syntax for a couple of user attribution clauses in changelog.d
After using Sphinx v7.2.6 (to workaround #2240) to build the `pip-tools` documentation, there seem to be a few changelog entries where the user attributions are not displayed as expected:

Image

#### Environment Versions

1. OS: Debian Linux (`forky` / `testing`)
1. Python version: `Python 3.13.7`
1. pip version: `pip 25.1`
1. pip-tools version: `pip-compile, version 7.5.1.dev28+dirty`
1. Sphinx version: `sphinx-build 7.2.6`

#### Steps to replicate

1. Set the working directory to the `docs` dir.
2. `pip install -r requirements.txt`
3. `pip install -e ..  # ensure pip-tools itself is installed as a package`
4. `pip install sphinx-build==7.2.6`
5. `sphinx-build -b html . _build`

#### Expected result

GitHub usernames should be hyperlinked in the attribution details next to each changelog entry in the HTML output.

#### Actual result

Some of the changelog entries -- particularly where a `:user:` directive is present instead of `{user}` directive -- seem to appear without a hyperlink attached to them.

For example, the `Fix an incompatibility ...` changelog entry in the screenshot, from change note file `2235.bugfix.md`, does not have a hyperlink and displays the literal `:user:` directive in the output to the reader.

### PR DESCRIPTION
**Pull request by jayaddison**
The migration to towncrier in #2203 included a couple of synthetic change note examples.

Now that `towncrier` is in use and some changes that use it ~~are soon to land~~ have landed in `pip-tools`, we can update the examples so that they hyperlink to genuine pull requests.

This is intended to aid contributors by providing them with more accurate, representative examples to crib from.

No changelog needed.

##### Contributor checklist

- [ ] ~~Included tests for the changes.~~
- [ ] ~~A change note is created in `changelog.d/` (see [`changelog.d/README.md`](https://github.com/jazzband/pip-tools/blob/main/changelog.d/#readme) for instructions)~~ or the PR text says "no changelog needed".

##### Maintainer checklist

- [x] If no changelog is needed, apply the `skip-changelog` label.
- [x] Assign the PR to an existing or new milestone for the target version (following [Semantic Versioning](https://blog.versioneye.com/2014/01/16/semantic-versioning/)).

##### Additional fixes
Two problems encountered while testing this are currently resolved by this branch:

- Resolves #2240.
- Resolves #2241.

### CODE REVIEW

File: changelog.d/README.md [hunk 1]
```diff
@@ -62,18 +62,10 @@ Do your best and a maintainer can discuss this with you during review.
 
 ### Examples
 
-Example bugfix, `2082.bugfix.md`:
+Example contributor update, [`2214.contrib.md`](https://github.com/jazzband/pip-tools/pull/2214):
 
 ```md
-Fixed the ordering of format controls to preserve underlying `pip` behavior
--- by {user}`sethmlarson`.
-```
```
Comment (webknjaz) [inline changelog.d/README.md:70]: We could keep the first one w/o a PR link for now. I'd like us to still have several examples, not just one.

Comment (jayaddison) [reply changelog.d/README.md:70]: One more added; although strictly speaking, one of the examples isn't yet merged; I'll hold this open for a little while longer.

**Comment by webknjaz** [comment]
@jayaddison could you rebase instead of pushing merge commits into the topic branch?

File: changelog.d/README.md [hunk 2]
```diff
@@ -62,18 +62,17 @@ Do your best and a maintainer can discuss this with you during review.
...
+of ``pip-compile`` -- by {user}`sirosen`.
 ```
 
-Example contributor update, `2202.contrib.md`:
+Example contributor update, [`2214.contrib.md`](https://github.com/jazzband/pip-tools/pull/2214):
 
 ```md
-`pip-tools` now uses [`sphinx-issues`](https://github.com/sloria/sphinx-issues)
-to link to issues, PRs, commits, and user accounts
+`pip-tools` now tests on and officially supports `pip` version 25.2 .
```
Comment (webknjaz) [inline changelog.d/README.md]: Stray whitespace and an illegal trailing period?

**Comment by jayaddison** [comment]
> @jayaddison could you rebase instead of pushing merge commits into the topic branch?

Will do on next push; thanks :+1:

File: changelog.d/README.md (hunk 2 above)
Comment (jayaddison) [reply changelog.d/README.md]: Mm.  It does disambiguate/demarcate the end of the version number (`25.2`), though..

An option could be to rephrase it to something like: _version 25.2 of `pip`_ -- although if we do that, perhaps we should change the original changelog entry too, for consistency.

Comment (webknjaz) [reply changelog.d/README.md]: Yeah, I suppose we could do that.

Comment (webknjaz) [reply changelog.d/README.md]: Actually, that period is unnecessary before the em-dash
```suggestion
`pip-tools` now tests on and officially supports `pip` version 25.2
```

**Comment by jayaddison** [comment]
Thanks again @sirosen!

File: docs/requirements.txt [hunk 3]
```diff
@@ -72,7 +72,7 @@ snowballstemmer==2.2.0
     # via sphinx
 soupsieve==2.4.1
     # via beautifulsoup4
-sphinx==7.2.2
+sphinx==7.2.6
```
Comment (webknjaz) [inline docs/requirements.txt:75]: This should've been bumped separately. There's no evidence of Sphinx breaking in CI/RTD: https://app.readthedocs.org/projects/pip-tools/builds/. And it's unrelated.

File: changelog.d/2235.bugfix.md [hunk 4]
```diff
@@ -1,2 +1,2 @@
 Fix an incompatibility with ``click >= 8.3`` which made ``pip-compile`` display incorrect
```
Comment (webknjaz) [inline changelog.d/2235.bugfix.md:1]: @jayaddison the double backticks should've been fixed here. We missed this in review.

File: changelog.d/README.md [hunk 5]
```diff
@@ -62,19 +62,17 @@ Do your best and a maintainer can discuss this with you during review.
...
 ### Examples
 
-Example bugfix, `2082.bugfix.md`:
+Example bugfix, [`2223.bugfix.md`](https://github.com/jazzband/pip-tools/pull/2224):
 
 ```md
-Fixed the ordering of format controls to preserve underlying `pip` behavior
--- by {user}`sethmlarson`.
+Fixed a bug which removed slashes from URLs in ``-r`` and ``-c`` in the output
+of ``pip-compile`` -- by {user}`sirosen`.
```
Comment (webknjaz) [inline changelog.d/README.md:69]: @jayaddison the double backticks should've been fixed here. We missed this in review.

Comment (jayaddison) [reply changelog.d/README.md:69]: Drats - sorry for missing that.  I notice the fixup is already handled by #2263; thank you.
